### ISSUE TITLE
Java services run with errors

### ISSUE THREAD

**Issue by wuyongdec** [ewolff/microservice-istio#3]
kubectl logs order-6bc8b4647c-bpwx5 order

` HikariPool-1 - Exception during pool initialization.

org.postgresql.util.PSQLException: FATAL: database "dborder" does not exist
        at `

It seems that the postgres pod does not init the shell script to create the database.

`LOG:  database system was interrupted; last known up at 2019-09-05 06:23:08 UTC
LOG:  database system was not properly shut down; automatic recovery in progress
LOG:  redo starts at 0/14EFC40
LOG:  invalid record length at 0/14EFC68: wanted 24, got 0
LOG:  redo done at 0/14EFC40
LOG:  last completed transaction was at log time 2019-09-05 06:23:08.268566+00
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
FATAL:  database "dbinvoicing" does not exist
FATAL:  database "dborder" does not exist
FATAL:  database "dbinvoicing" does not exist
FATAL:  database "dborder" does not exist
`

**Comment by ewolff** [comment]
Thanks for reporting. Please delete the Postgres Pod and try again. `kubectl get pods` gives the names of the pods, `kubectl delete pod <pod-name>` removes the pods.

**Comment by wuyongdec** [comment]
#

> Thanks for reporting. Please delete the Postgres Pod and try again. `kubectl get pods` gives the names of the pods, `kubectl delete pod <pod-name>` removes the pods.

Sorry ewolff ,I don't really understand the reason why should I delete the Postgres pod. The oringnal problem seems the db init script does not create succeessfully.

**Comment by ewolff** [comment]
This will delete the pod and a new one will be created. During the creation the script should run. I want to make sure the problem is reproducible as I use the setup, too, and it works for me.

**Comment by wuyongdec** [comment]
Thanks，Ewolff.  I did the steps as your said , but get the same result that the db init failed.
My evironment is win10 docker desktop v2.1.0.1
docker engine:19.03.1
k8s:  v1.14.3
istio: v1.2.5

**Comment by wuyongdec** [comment]
The same evironment on mac os works well.

**Comment by ewolff** [comment]
Excellent - glad the problem is solved! 👍🙂
