### ISSUE TITLE
Request without POST or GET 

### ISSUE THREAD

**Issue by akondasif** [ewolff/microservice-istio#6]
Hi @ewolff ,

We followed your recommendations from [this issue](https://github.com/ewolff/microservice/issues/28) and found a few instances of request method without get or post

Source:

https://github.com/ewolff/microservice-istio/blob/7f014b319b3bdc8c704dfd3c8c927c3ad9e94d5b/microservice-istio-demo/microservice-istio-invoicing/src/main/java/com/ewolff/microservice/invoicing/web/InvoiceController.java#L28 

and 

https://github.com/ewolff/microservice-istio/blob/7f014b319b3bdc8c704dfd3c8c927c3ad9e94d5b/microservice-istio-demo/microservice-istio-order/src/main/java/com/ewolff/microservice/order/logic/OrderRestController.java#L36

and 

https://github.com/ewolff/microservice-istio/blob/7f014b319b3bdc8c704dfd3c8c927c3ad9e94d5b/microservice-istio-bonus/src/main/java/com/ewolff/microservice/bonus/web/BonusController.java#L28

and 

https://github.com/ewolff/microservice-istio/blob/7f014b319b3bdc8c704dfd3c8c927c3ad9e94d5b/microservice-istio-demo/microservice-istio-order/src/main/java/com/ewolff/microservice/order/logic/OrderController.java#L45

and 

https://github.com/ewolff/microservice-istio/blob/7f014b319b3bdc8c704dfd3c8c927c3ad9e94d5b/microservice-istio-demo/microservice-istio-shipping/src/main/java/com/ewolff/microservice/shipping/web/ShippingController.java#L28

and 

https://github.com/ewolff/microservice-istio/blob/7f014b319b3bdc8c704dfd3c8c927c3ad9e94d5b/microservice-istio-demo/microservice-istio-invoicing/src/main/java/com/ewolff/microservice/invoicing/web/InvoiceController.java#L28

**Comment by ewolff** [comment]
As mentioned https://github.com/ewolff/microservice/issues/28#issuecomment-654375293 I don't think this is a security problem. Please reopen if you have different information. Thanks.
